### ISSUE TITLE
Epic: Parsable Bill Statements

### ISSUE THREAD

**Issue by mrsauravsahu** [payobills/payobills#94]
# Major Features

Note: This will create duplicated transactions and we are okay with that for now - until deduplication service becomes a thing

High level changes needed

## Infra
- ~~MinIO service for storing PDFs~~ (Decided to use NocoDB to store files)
- ~~RabbitMQ for async messaging~~ -> this was already setup by kube-homelab and also saves data to a PVC

## Backend
- [x] #174
- [x] #178
- [x] #177

## UI
- [x] #200
- [x] #201

- [x] UI: Login with KeyCloak
- [x] ~~Authenticate all APIs with jwt from KeyCloak~~ -> deferred till next release
- [x] ~~Gateway 0.1.0: payobills APIs accessible only through Gateway~~ -> deferred till next release

## Files 0.2.0
- [x] Uploading files to NocoDB
- [x] ~~Move files to the right container after it is accepted for use (bills accepts pdf file from tmp-uploads)~~

## OCR Service 0.1.0

- Create a new OCR service to ocr files as they are uploaded, the ocr service should listen on the same event as the file service writes, and OCR will be on by default.
- Maybe a metadata property in the message can be used to opt-out from OCR

## External Dependencies
- [x] ~~Setup RabbitMQ in kube-homelab~~

![Image](https://github.com/user-attachments/assets/37928e34-4775-4865-bb2f-f565c0eab361)

# Details

- payments ms to be filled with data from parsing of the PDF bills and not bills ms.
- ~~files service will store the data to a folder - fine to be a local folder for now, but would also be good to use a PVC from openEBS (just like how homelab sets up external apps)~~ files service stores the file in MinIO

- The gateway automatically transforming `File` types to string by auto uploading to File service looks a bit complicated, based on https://the-guild.dev/graphql/mesh/docs/transforms/transforms-introduction, for now, the UI will have to upload the file first, and then call the appropriate mutation. Will spike it for v0.5.0

**Comment by mrsauravsahu** [comment]
- payments ms to be filled with data from parsing of the PDF bills and not bills ms.
- files service will store the data to a folder - fine to be a local folder for now, but would also be good to use a PVC from openEBS (just like how homelab sets up external apps)

**Comment by mrsauravsahu** [comment]
- The gateway automatically transforming `File` types to string by auto uploading to File service looks a bit complicated, based on https://the-guild.dev/graphql/mesh/docs/transforms/transforms-introduction, for now, the UI will have to upload the file first, and then call the appropriate mutation. Will spike it for v0.4.0

**Comment by mrsauravsahu** [comment]
Note: This will create duplicated transactions and we are okay with that for now - until deduplication service becomes a thing

High level changes needed

## Infra
- ~~MinIO service for storing PDFs~~ (Decided to use NocoDB to store files)
- RabbitMQ for async messaging

## Backend
- [ ] #174
- [ ] CRON which parses whenever a new file is uploaded

## UI
- [ ] Ability to upload files to a specific bill
- [ ] See all transactions parsed from a statement

**Comment by mrsauravsahu** [comment]
Removing notifications from `0.4.0` - #193

**Comment by mrsauravsahu** [comment]
Closing as all sub issues are completed. Any new work on bill statements will show up as a new Epic
